NumPy: Numerical Python

In [2]:
import numpy as np

### 1. Data Types and Attributes

In [3]:
# Numpy's main datatype is ndarray

# (1,3)
a1 = np.array([1, 2, 3])
a1, type(a1), a1.shape, a1.ndim

(array([1, 2, 3]), numpy.ndarray, (3,), 1)

In [4]:
# (2,3)
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]
              ]
             )
a2, type(a2) , a2.shape, a2.ndim

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 numpy.ndarray,
 (2, 3),
 2)

In [5]:
# (2,3,3)
a3 = np.array([
               [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],

              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]
              ] 
             )
a3, type(a3), a3.shape, a3.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 numpy.ndarray,
 (2, 3, 3),
 3)

In [6]:
# (3,2,3)
a3_1 = np.array([
               [[1, 2, 3],
               [4, 5, 6]],
    
               [[7, 8, 9],
               [10, 11, 12]],
    
               [[13, 14, 15],
               [16, 17, 18]]
              ] 
             )
a3_1, type(a3_1) , a3_1.shape, a3_1.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 numpy.ndarray,
 (3, 2, 3),
 3)

In [7]:
# (2,2,2,3)
a4 = np.array([
               [
               [[1, 2, 3],
               [4, 5, 6]],

                [[7, 8, 9],
                [7, 8, 9]]
               ],

              [
               [[10, 11, 12],
               [13, 14, 15]],

               [[16, 17, 18],
                [16, 17, 18]]
              ] 
])
a4, type(a4), a4.shape, a4.ndim

(array([[[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [ 7,  8,  9]]],
 
 
        [[[10, 11, 12],
          [13, 14, 15]],
 
         [[16, 17, 18],
          [16, 17, 18]]]]),
 numpy.ndarray,
 (2, 2, 2, 3),
 4)

In [7]:
# data type
a1.dtype, a2.dtype, a3.dtype, a4.dtype

(dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'))

In [8]:
# number of elements in the arrays
a1.size, a2.size, a3.size, a4.size

(3, 6, 18, 24)

In [9]:
# datatype
type(a1), type(a2), type(a3), type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
# Create a Dataframe from a NumPy array

import pandas as pd

df = pd.DataFrame(a2)
df


0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### 2. Creating Arrays


In [10]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array = np.arange(0, 10, 2)  # RETURN EQAULLY SPACED NUMBERS
range_array

array([0, 2, 4, 6, 8])

In [13]:
random_array = np.random.randint(0, 10, (3,5)) # RETURN RANDOM INTEGERS OF SPECIFIDE SIZE
random_array

array([[8, 0, 6, 6, 7],
       [6, 9, 8, 5, 9],
       [7, 8, 0, 7, 7]])

In [14]:
random_array2 = np.random.random((5,3))  # RETURN RANDOM NUMBERS IN [0,1)
random_array2

array([[0.87097615, 0.10248063, 0.45646435],
       [0.28282552, 0.75332809, 0.38029904],
       [0.21691139, 0.91187776, 0.62322212],
       [0.70859613, 0.09203463, 0.06457735],
       [0.58227775, 0.64109055, 0.70208543]])

In [17]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.24040965, 0.66888234, 0.46267044],
       [0.18368531, 0.04009998, 0.33530835],
       [0.24392345, 0.82199744, 0.93841573],
       [0.34486977, 0.37981632, 0.22642255],
       [0.39190281, 0.18506601, 0.76353626]])

In [20]:
random_array

array([[8, 0, 6, 6, 7],
       [6, 9, 8, 5, 9],
       [7, 8, 0, 7, 7]])

In [21]:
np.unique(random_array)

array([0, 5, 6, 7, 8, 9])

In [23]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array = np.random.randint(0, 10, (3,5)) # RETURN RANDOM INTEGERS OF SPECIFIDE SIZE
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

### 3. Viewing Arrays and Matices

In [24]:
a1

array([1, 2, 3])

In [25]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
a1[0], a1[1], a1[2]

(1, 2, 3)

In [27]:
a2[0]

array([1. , 2. , 3.3])

In [24]:
a2[1]

array([4. , 5. , 6.5])

In [28]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [29]:
a3.shape

(2, 3, 3)

In [30]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
 a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [32]:
  # Accessing the first column of a3[0]
a3[0][:,0]

array([1, 4, 7])

In [33]:
#or
a3[0,:,0]

array([1, 4, 7])

In [34]:
a3[0][0]  # Accessing the first row of a3[0]

array([1, 2, 3])

In [35]:
# Or
a3[0,0,:]

array([1, 2, 3])

In [36]:
# all the first columns
a3[:,:,:1]

array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]]])

In [34]:
# all the first rows
a3[:,:1,:]

array([[[ 1,  2,  3]],

       [[10, 11, 12]]])

In [37]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [38]:
a3[1,1,2]

15

In [39]:
a3[0,1,1]

5

In [40]:
a5 = np.random.randint(10, size=(2,3,4,5))
a5

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [41]:
a5.shape, a5.ndim

((2, 3, 4, 5), 4)

In [42]:
# Get the first 4 numbers of the inner most arrays
a5[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

In [43]:
a5[:,:,:,:1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])

In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [45]:
a2.shape

(2, 3)

In [47]:
a2[:1,:]

array([[1. , 2. , 3.3]])

In [48]:
a2[:,:1]

array([[1.],
       [4.]])

In [49]:
a2[:,:2]

array([[1., 2.],
       [4., 5.]])

In [50]:
a2[:,1:3]

array([[2. , 3.3],
       [5. , 6.5]])

# 4. Manipulating & Comparing Arrays 

### Arithmetic

In [51]:
a1, a1.shape

(array([1, 2, 3]), (3,))

In [52]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [53]:
a1 +ones

array([2., 3., 4.])

In [54]:
a1 - ones

array([0., 1., 2.])

In [55]:
a1 * ones

array([1., 2., 3.])

In [53]:
a2, a2.shape

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 (2, 3))

In [56]:
a1 * a2   # Component-wise multiplication

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [57]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [56]:
# Check how to reshape arrays
a3*a2

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [58]:
a1 / ones

array([1., 2., 3.])

In [59]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [60]:
# Floor division rounds down and remove the decimal
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [61]:
# Power
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [63]:
a1

array([1, 2, 3])

In [62]:
a1 % 2

array([1, 0, 1])

In [67]:
a1 /2

array([0.5, 1. , 1.5])

In [68]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [69]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [70]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

21.8

### Aggregation

In [74]:
listy_list = [1,2,3]
sum(listy_list)

6

In [78]:
np.sum(listy_list)

6

In [75]:
a1

array([1, 2, 3])

In [76]:
sum(a1)

6

In [77]:
np.sum(a1)

6

### Use Python methods (here, `sum()`) on Python datatypes and use NumPy methods on NumPy arrays (here `np.sum()`).

In [79]:
# Creat a massive NumPy Array
massive_array = np.random.random(100000)
massive_array.size

100000

In [80]:
massive_array[:100]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839,
       0.63892108, 0.89155444, 0.68005557, 0.44919774, 0.97857093,
       0.11620191, 0.7670237 , 0.41182014, 0.67543908, 0.24979628,
       0.31321833, 0.96541622, 0.58846509, 0.65966841, 0.53320625,
       0.23053302, 0.39486929, 0.61880856, 0.47486752, 0.47013219,
       0.71607453, 0.287991  , 0.38346223, 0.74916984, 0.87845219,
       0.10286336, 0.09237389, 0.35404666, 0.55181626, 0.03362509,
       0.96896177, 0.32099724, 0.22126269, 0.1412639 , 0.09725993,
       0.98404224, 0.26034093, 0.53702252, 0.44792617, 0.09956909,
       0.35231166, 0.46924917, 0.84114013, 0.90464774, 0.03755938,
       0.50831545, 0.16684751, 0.77905102, 0.8649333 , 0.41139672,
       0.13997259, 0.03322239, 0.98257496, 0.37329075, 0.42007537,
       0.05058812, 0.36549611, 0.01662797, 0.23074234, 0.7649117 ,
       0.94412352, 0.74999925, 0.33940382, 0.48954894, 0.33898

In [81]:
%timeit sum(massive_array)   # Python sum
%timeit np.sum(massive_array) # Numpy sum

5.15 ms ± 76.3 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
17.5 μs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [82]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [83]:
np.mean(a2)

3.6333333333333333

In [84]:
np.max(a2)

6.5

In [85]:
np.min(a2)

1.0

In [86]:
np.std(a2)

1.8226964152656422

In [87]:
np.var(a2)

3.3222222222222224

In [89]:
np.sum(a2, axis = 0)

array([5. , 7. , 9.8])

In [90]:
np.sum(a2, axis = 1)

array([ 6.3, 15.5])

### Reshape and Transpose

In [91]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [92]:
a2.shape

(2, 3)

In [93]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [94]:
a3.shape

(2, 3, 3)

### Broadcasting rule
Two array are compatible for multiplication if:

* They have the same shape, or
* One of the dimensions of one of the array is 1.

In [95]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [96]:
a2_reshape.shape

(2, 3, 1)

In [97]:
a2_reshape *a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [88]:
a3*a2_reshape

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [89]:
# Transpose
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [90]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [91]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [92]:
a3.T.shape

(3, 3, 2)

In [93]:
a3.shape

(2, 3, 3)

### Dot Product

In [94]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [95]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [96]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [97]:
#Element-wise multiplication (Hadamard product)
mat1* mat2     

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [98]:
# Dot product

np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [99]:
# Transpose mat1
mat1_T = mat1.T

In [100]:
mat1_T.shape, mat2.shape

((3, 5), (5, 3))

In [101]:
np.dot(mat1_T, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [102]:
mat1_T @ mat2

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [103]:
mat2 @ mat1_T

array([[ 51, 130,  67, 115, 111],
       [ 55,  76,  39,  69,  77],
       [ 72, 164,  85, 146, 145],
       [ 20,  33,  27,  37,  56],
       [ 15,  44,  34,  47,  64]])

### Dot Product Example (Nut butter sales)

In [104]:
np.random.seed(0)

# Number of jars sold
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [105]:
# create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amount, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [106]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [107]:
# Create Prices dataframe
butter_prices = pd.DataFrame(prices.reshape((1,3)), index=["Price"], columns=["Almond butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [108]:
weekly_sales.shape

(5, 3)

In [109]:
prices.shape

(3,)

In [110]:
Total_sales = weekly_sales.dot(prices)
Total_sales

Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142
dtype: int64

In [111]:
Total_sales.shape

(5,)

In [112]:
weekly_sales["Total ($)"] = Total_sales
weekly_sales

Almond butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

### Comparison Operator

In [114]:
a1

array([1, 2, 3])

In [115]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [119]:
bool_array= a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [121]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [122]:
a1 == a1

array([ True,  True,  True])

In [123]:
a1 > a1

array([False, False, False])

### 5. Sorting

In [124]:
randdom_array = np.random.randint(10, size=(3,5))
randdom_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [125]:
np.sort(randdom_array) # sort the value of the arrays

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [126]:
np.argsort(randdom_array)  # Provide the original index of the elements in the sorted array

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [128]:
np.argmin(a1)

0

In [129]:
np.argmax(a1)

2

In [130]:
a1

array([1, 2, 3])

In [134]:
np.argmin(randdom_array, axis=0) # argmin along the rows

array([2, 2, 2, 2, 1])

In [135]:
np.argmin(randdom_array, axis=1) # argmin along the columns

array([2, 4, 2])

In [136]:
np.argmax(randdom_array, axis=1)

array([4, 1, 1])

### 6. Practical Example - Turning Image into Numpy Arrays

![panda](/home/ogonna/Desktop/Udemy_ML_and_DS/panda.png)


In [154]:
from matplotlib.image import imread
panda = imread("/home/ogonna/Desktop/Udemy_ML_and_DS/panda.png") 
print(type(panda))

<class 'numpy.ndarray'>


In [156]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [157]:
panda.shape

(2330, 3500, 3)

In [158]:
panda.ndim

3

In [159]:
panda.size

24465000

In [171]:
panda[:2,:5,:3]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]]], dtype=float32)

<img src="/home/ogonna/Desktop/Udemy_ML_and_DS/car-photo.png"/>

In [172]:
car = imread("/home/ogonna/Desktop/Udemy_ML_and_DS/car-photo.png") 
print(type(car))

<class 'numpy.ndarray'>


In [173]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [174]:
car.shape

(431, 575, 4)

In [175]:
car.ndim

3

In [176]:
car.size

991300

In [179]:
car[:2,:5,:4]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        [0.1764706 , 0.19215687, 0.10980392, 1.        ],
        [0.19215687, 0.20784314, 0.12941177, 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        [0.19215687, 0.2       , 0.12941177, 1.        ],
        [0.21176471, 0.21960784, 0.16078432, 1.        ]]], dtype=float32)

In [180]:
dog = imread("/home/ogonna/Desktop/Udemy_ML_and_DS/dog-photo.png") 
print(type(dog))

<class 'numpy.ndarray'>


In [181]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [182]:
dog.shape

(432, 575, 4)

In [183]:
dog.ndim

3

In [184]:
dog.size

993600